// flow-typed signature: 20a651b1c6e40d970790ba77c87e058d
// flow-typed version: <<STUB>>/bpk-component-text_vlatest/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bpk-component-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bpk-component-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bpk-component-text/src/BpkText-test' {
  declare module.exports: any;
}

declare module 'bpk-component-text/src/BpkText' {
  declare module.exports: any;
}

declare module 'bpk-component-text/stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bpk-component-text/index' {
  declare module.exports: $Exports<'bpk-component-text'>;
}
declare module 'bpk-component-text/index.js' {
  declare module.exports: $Exports<'bpk-component-text'>;
}
declare module 'bpk-component-text/src/BpkText-test.js' {
  declare module.exports: $Exports<'bpk-component-text/src/BpkText-test'>;
}
declare module 'bpk-component-text/src/BpkText.js' {
  declare module.exports: $Exports<'bpk-component-text/src/BpkText'>;
}
declare module 'bpk-component-text/stories.js' {
  declare module.exports: $Exports<'bpk-component-text/stories'>;
}
