// flow-typed signature: a8dadda8bb8ab2d582624160a9e94855
// flow-typed version: <<STUB>>/bpk-component-list_vlatest/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bpk-component-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bpk-component-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bpk-component-list/src/BpkList-test' {
  declare module.exports: any;
}

declare module 'bpk-component-list/src/BpkList' {
  declare module.exports: any;
}

declare module 'bpk-component-list/src/BpkListItem-test' {
  declare module.exports: any;
}

declare module 'bpk-component-list/src/BpkListItem' {
  declare module.exports: any;
}

declare module 'bpk-component-list/stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bpk-component-list/index' {
  declare module.exports: $Exports<'bpk-component-list'>;
}
declare module 'bpk-component-list/index.js' {
  declare module.exports: $Exports<'bpk-component-list'>;
}
declare module 'bpk-component-list/src/BpkList-test.js' {
  declare module.exports: $Exports<'bpk-component-list/src/BpkList-test'>;
}
declare module 'bpk-component-list/src/BpkList.js' {
  declare module.exports: $Exports<'bpk-component-list/src/BpkList'>;
}
declare module 'bpk-component-list/src/BpkListItem-test.js' {
  declare module.exports: $Exports<'bpk-component-list/src/BpkListItem-test'>;
}
declare module 'bpk-component-list/src/BpkListItem.js' {
  declare module.exports: $Exports<'bpk-component-list/src/BpkListItem'>;
}
declare module 'bpk-component-list/stories.js' {
  declare module.exports: $Exports<'bpk-component-list/stories'>;
}
