// flow-typed signature: 754d044d87bc773ff177dce69c4f5bf4
// flow-typed version: <<STUB>>/bpk-component-popover_vlatest/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bpk-component-popover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bpk-component-popover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bpk-component-popover/src/BpkPopover-test' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/BpkPopover' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/BpkPopoverPortal-test' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/BpkPopoverPortal' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/constants' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/themeAttributes-test' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/src/themeAttributes' {
  declare module.exports: any;
}

declare module 'bpk-component-popover/stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bpk-component-popover/index' {
  declare module.exports: $Exports<'bpk-component-popover'>;
}
declare module 'bpk-component-popover/index.js' {
  declare module.exports: $Exports<'bpk-component-popover'>;
}
declare module 'bpk-component-popover/src/BpkPopover-test.js' {
  declare module.exports: $Exports<'bpk-component-popover/src/BpkPopover-test'>;
}
declare module 'bpk-component-popover/src/BpkPopover.js' {
  declare module.exports: $Exports<'bpk-component-popover/src/BpkPopover'>;
}
declare module 'bpk-component-popover/src/BpkPopoverPortal-test.js' {
  declare module.exports: $Exports<
    'bpk-component-popover/src/BpkPopoverPortal-test',
  >;
}
declare module 'bpk-component-popover/src/BpkPopoverPortal.js' {
  declare module.exports: $Exports<
    'bpk-component-popover/src/BpkPopoverPortal',
  >;
}
declare module 'bpk-component-popover/src/constants.js' {
  declare module.exports: $Exports<'bpk-component-popover/src/constants'>;
}
declare module 'bpk-component-popover/src/themeAttributes-test.js' {
  declare module.exports: $Exports<
    'bpk-component-popover/src/themeAttributes-test',
  >;
}
declare module 'bpk-component-popover/src/themeAttributes.js' {
  declare module.exports: $Exports<'bpk-component-popover/src/themeAttributes'>;
}
declare module 'bpk-component-popover/stories.js' {
  declare module.exports: $Exports<'bpk-component-popover/stories'>;
}
