// flow-typed signature: d4ce92f2cd05c5be314abaafcd2ee98a
// flow-typed version: <<STUB>>/bpk-component-button_vlatest/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bpk-component-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bpk-component-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bpk-component-button/src/BpkButton-test' {
  declare module.exports: any;
}

declare module 'bpk-component-button/src/BpkButton' {
  declare module.exports: any;
}

declare module 'bpk-component-button/src/themeAttributes-test' {
  declare module.exports: any;
}

declare module 'bpk-component-button/src/themeAttributes' {
  declare module.exports: any;
}

declare module 'bpk-component-button/stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bpk-component-button/index' {
  declare module.exports: $Exports<'bpk-component-button'>;
}
declare module 'bpk-component-button/index.js' {
  declare module.exports: $Exports<'bpk-component-button'>;
}
declare module 'bpk-component-button/src/BpkButton-test.js' {
  declare module.exports: $Exports<'bpk-component-button/src/BpkButton-test'>;
}
declare module 'bpk-component-button/src/BpkButton.js' {
  declare module.exports: $Exports<'bpk-component-button/src/BpkButton'>;
}
declare module 'bpk-component-button/src/themeAttributes-test.js' {
  declare module.exports: $Exports<
    'bpk-component-button/src/themeAttributes-test',
  >;
}
declare module 'bpk-component-button/src/themeAttributes.js' {
  declare module.exports: $Exports<'bpk-component-button/src/themeAttributes'>;
}
declare module 'bpk-component-button/stories.js' {
  declare module.exports: $Exports<'bpk-component-button/stories'>;
}
